import os
os.chdir(r'c:\Users\kunji\NODE')

with open('sih-frontend/src/components/Navbar.jsx', 'a') as f:
    f.write('/* Navbar component */\n')
    f.write('import { useState } from "react";\n')
    f.write('import { signOut } from "aws-amplify/auth";\n')
    f.write('import { getClearanceBadgeClass, getUnitBadgeClass } from "../services/api";\n\n')
    f.write('export default function Navbar({ user, activeView, onViewChange, onLogout, onRoleSwitch, demoMode=false, demoRole }) {\n')
    f.write('  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);\n\n')
    f.write('  const navTabs = [\n')
    f.write('    { id: "personnel", label: "Personnel Directory", roles: ["Admin"] },\n')
    f.write('    { id: "assets", label: "Asset Inventory", roles: ["Admin", "Manager", "Auditor"] },\n')
    f.write('    { id: "custody", label: "Custody and Transfers", roles: ["Admin", "Manager"] },\n')
    f.write('    { id: "audit", label: "Audit Ledger", roles: ["Admin", "Manager", "Auditor"] },\n')
    f.write('    { id: "verify", label: "LMV Verifier", roles: ["Admin", "Manager", "Auditor", "User"] },\n')
    f.write('  ];\n\n')
    f.write('  const userRole = user?.attributes?.["custom:role"] || user?.role || "User";\n')
    f.write('  const availableTabs = navTabs.filter(tab => tab.roles.includes(userRole));\n\n')
    f.write('  const clearance = user?.attributes?.["custom:clearanceLevel"] || "UNCLASSIFIED";\n')
    f.write('  const unit = user?.attributes?.["custom:unit"] || "ARMY";\n')
    f.write('  const compartments = (user?.attributes?.["custom:compartments"] || "").split(",").filter(Boolean);\n\n')
    f.write('  const demoRoles = [\n')
    f.write('    { id: "admin", name: "Col. Rajesh", role: "Admin", clearance: "TOP_SECRET", unit: "BEL_LABS", avatar: "STAR" },\n')
    f.write('    { id: "manager", name: "Maj. Vikram", role: "Manager", clearance: "SECRET", unit: "ARMY", compartments: ["PROJECT_BRAHMOS"], avatar: "DIAMOND" },\n')
    f.write('    { id: "auditor", name: "Capt. Ananya", role: "Auditor", clearance: "SECRET", unit: "ARMY", avatar: "DOT" },\n')
    f.write('    { id: "custodian", name: "WO Sharma", role: "User", clearance: "CONFIDENTIAL", unit: "ARMY", avatar: "TRIANGLE" },\n')
    f.write('  ];\n\n')
    f.write('  const handleLogout = async () => {\n')
    f.write('    try { await signOut({ global: true }); onLogout?.(); }\n')
    f.write('    catch (error) { console.error("Logout failed:", error); onLogout?.(); }\n')
    f.write('  };\n\n')

print('Part 1 written')